from app.exeptions.auth_exeptions import AuthApiError, SupabaseException
